// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDuIy0qPhiipKC5yKh4UfYJX7_6OXj3A3Y',
    appId: '1:340243273727:android:356bf54639ebf3e6d3f9ca',
    messagingSenderId: '340243273727',
    projectId: 'book-hub-c017b',
    storageBucket: 'book-hub-c017b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT6uf7s9AJu3TzrSgNYPsvNi-X-5Dh9pI',
    appId: '1:340243273727:ios:12391dfb47412168d3f9ca',
    messagingSenderId: '340243273727',
    projectId: 'book-hub-c017b',
    storageBucket: 'book-hub-c017b.appspot.com',
    androidClientId: '340243273727-mgjst07an4sf12nk00sjrt64ma5okiij.apps.googleusercontent.com',
    iosClientId: '340243273727-1j7ao5npm6ihjl6jlo5sc58obl53ir7r.apps.googleusercontent.com',
    iosBundleId: 'com.example.weChat',
  );

}